services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    env_file:
      - ./sql.env
    ports:
      - "1433:1433"
    networks:
      - taskmanager-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - ./rabbitmq.env
    networks:
      - taskmanager-net

  taskmanager-api:
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
    container_name: taskmanager-api
    ports:
      - "7015:8080"
    depends_on:
      - sqlserver
      - rabbitmq
    env_file:
      - ./api.env
    networks:
      - taskmanager-net

volumes:
  sql_data:

networks:
  taskmanager-net:
    driver: bridge
