services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    env_file:
      - ./sql.env
    # environment:
    #   SA_PASSWORD: "Task@12345"
    #   ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # volumes:
    #   - sql_data:/var/opt/mssql
    networks:
      - taskmanager-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - taskmanager-net

  taskmanager-api:
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
    container_name: taskmanager-api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - rabbitmq
    env_file:
      - ./api.env
    networks:
      - taskmanager-net

volumes:
  sql_data:

networks:
  taskmanager-net:
    driver: bridge
